name: Jetsurvey

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/Jetsurvey.yaml'
      - 'Jetsurvey/**'
  pull_request:
    paths:
      - '.github/workflows/Jetsurvey.yaml'
      - 'Jetsurvey/**'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-sample.yml
    with:
      name: Jetsurvey
      path: Jetsurvey
    secrets:
      compose_store_password: ${{ secrets.COMPOSE_STORE_PASSWORD }}
      compose_key_alias: ${{ secrets.COMPOSE_KEY_ALIAS }}
      compose_key_password: ${{ secrets.COMPOSE_KEY_PASSWORD }}
